### ISSUE TITLE
Release 0.0.2

### ISSUE THREAD

**Issue by mschinis** [nicksrandall/babel-polyfill#2]
Hello,
You released a new 0.0.2 version, but bower will refuse to pick it up because you need to create another github release!

Thanks,
Michael

**Comment by julkue** [comment]
This repo seems to be not maintained anymore. You will have more luck switching to the original npm version.

**Comment by mschinis** [comment]
yeah, I ended up using babel's maintained repository.

**Comment by nicksrandall** [comment]
Babel released a "packaged" version of their polyfill. Please use that: https://www.npmjs.com/package/babel-polyfill

**Comment by julkue** [comment]
The reason I looked at this repository was because I would like to use the polyfill with bower instead of npm.
